sudo : required
services :
  - docker

before_install : 
  - docker build -t tomna/react-test -f ./client/Dockerfile.dev ./client2

script : 
  - docker run tomna/react-test npm test -- --coverage

after_success: 
  - docker build -t tomna/multi-client ./client
  - docker build -t tomna/multi-nginx ./nginx
  - docker build -t tomna/multi-server ./server
  - docker build -t tomna/multi-worker ./worker
  - echo "$DOCKER_PASSWORD"  |  docker login -u "$DOCKER_ID" --password-stdin
  - docker push tomna/multi-client
  - docker push tomna/multi-nginx
  - docker push tomna/multi-server
  - docker push lim/multi-worker