sudo : required
services :
  - docker

before_install : 
  - docker build -t tomna/multi-client -f ./client/Dockerfile.dev ./client

script : 
  - docker run -e CI=true tomna/multi-client npm test -- --coverage

after_success: 
  - docker build -t tomna/multi-client ./client
  - docker build -t tomna/multi-nginx ./nginx
  - docker build -t tomna/multi-server ./server
  - docker build -t tomna/multi-worker ./worker
  - echo "$DOCKER_PASSWORD"  |  docker login -u "$DOCKER_ID" --password-stdin
  - docker push limhye/multi-client
  - docker push limhye/multi-nginx
  - docker push limhye/multi-server
  - docker push limhye/multi-worker

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

deploy:
  provider : elasticbeanstalk
  region : ap-northeast-2
  app : multi-docker
  env : MultiDocker-env
  bucket_name : elasticbeanstalk-ap-northeast-2-587909237394
  bucket_path : docker-multi
  on: 
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  edge: true
  provider: elasticbeanstalk